name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:

    runs-on: ubuntu-latest
    container:
      image: docker.io/ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - name: run tests
      run: cd tests && ./run-tests.sh
      
    - name: log results
      run: cat /tmp/sanoid_*.log
