name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: set up env
      run: sudo mkdir -p /lib/modules/5.15.0-1024-azure && sudo ln -s /lib/modules/$(uname -r) /lib/modules/5.15.0-57-generic && ls -lah /lib/modules
      
    - name: install required system packages
      run: sudo apt-get update && sudo apt-get -y install apt-utils build-essential git zfsutils-linux kmod zfs-dkms ca-certificates
  
    - name: set up zfs
      run:  ls -lah /lib/modules && ls -lah /lib/modules/$(uname -r) && modinfo zfs && sudo modprobe -vvv zfs
  
    - name: install perl deps
      run: sudo cpan install Config::IniFiles Capture::Tiny
      
    - name: install faketime
      run: git clone https://github.com/wolfcw/libfaketime && cd libfaketime && make && make install && cd ..
  
    - name: prepare env
      run: export LD_PRELOAD=/usr/local/lib/faketime/libfaketimeMT.so.1 && FAKETIME="-15d" date
  
    - name: run tests
      id: run_tests
      run: cd tests && ./run-tests.sh
      
    - name: log test results
      if: always() && steps.run_tests.outcome == 'failure'
      run: cat /tmp/sanoid_test_run_1_one_year.log && cat /tmp/sanoid_test_run_2_dst_handling.log
