name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:

    runs-on: ubuntu-latest
    container:
      image: docker.io/ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - name: install required system packages
      run: apt-get update && apt-get -y install apt-utils build-essential git zfsutils-linux zfs-dkms ca-certificates
  
    - name: set up zfs
      run: mkdir /lib/modules/5.15.0-1024-azure && cp -r /lib/modules/5.15.0-57-generic/* /lib/modules/5.15.0-1024-azure/ && modprobe zfs
  
    - name: install perl deps
      run: cpan install Config::IniFiles Capture::Tiny
      
    - name: install faketime
      run: git clone https://github.com/wolfcw/libfaketime /libfaketime && cd /libfaketime && make && make install
  
    - name: prepare env
      run: export LD_PRELOAD=/usr/local/lib/faketime/libfaketimeMT.so.1 && FAKETIME="-15d" date
  
    - name: run tests
      id: run_tests
      run: cd tests && ./run-tests.sh
      
    - name: log test results
      if: always() && steps.run_tests.outcome == 'failure'
      run: cat /tmp/sanoid_test_run_1_one_year.log && cat /tmp/sanoid_test_run_2_dst_handling.log
