name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:

    runs-on: ubuntu-latest
    container:
      image: docker.io/ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - name: install required packages
      run: apt-get update && apt-get -y install --no-install-recommends apt-utils build-essential git zfsutils-linux ca-certificates
      
    - name: install faketime
      run: git clone https://github.com/wolfcw/libfaketime /libfaketime && cd /libfaketime && make && make install
  
    - name: run tests
      run: cd tests && ./run-tests.sh
      
    - name: log results
      run: cat /tmp/sanoid_*.log
