name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:

    runs-on: ubuntu-latest
    container:
      image: docker.io/ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - name: install required system packages
      run: apt-get update && apt-get -y install apt-utils build-essential git zfsutils-linux zfs-dkms zfs-initramfs ca-certificates kmod
      
    - name: install perl deps
      run: cpan install Config::IniFiles
      
    - name: install faketime
      run: git clone https://github.com/wolfcw/libfaketime /libfaketime && cd /libfaketime && make && make install
  
    - name: prepare env
      run: /sbin/modprobe zfs && export LD_PRELOAD=/usr/local/lib/faketime/libfaketimeMT.so.1 && FAKETIME="-15d" && date
  
    - name: run tests
      run: cd tests && ./run-tests.sh
      
    - name: log test results
      run: cat /tmp/sanoid_test_run_1_one_year.log && cat /tmp/sanoid_test_run_2_dst_handling.log
