name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: run tests
      run: cd tests && ./run-tests.sh
