name: Tests

on:
  push:
  pull_request:

jobs:
  run:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: install perl deps
      run: sudo cpan install Config::IniFiles Capture::Tiny
      timeout-minutes: 20
      
    - name: install required system packages
      run: sudo apt-get update && sudo apt-get -y install apt-utils build-essential git zfsutils-linux kmod zfs-dkms ca-certificates && zfs --version
      
    - name: run tests
      id: run_tests
      run: cd tests && sudo ./run-tests.sh
      timeout-minutes: 60
      
    - name: log test results
      if: always() && steps.run_tests.outcome == 'failure'
      run: cat /tmp/sanoid_test_run_*.log
